#!/bin/bash
# Job for submitting process_tape5_files
#SBATCH --partition=serial
#SBATCH --export=ALL
#SBATCH --ntasks=1
#SBATCH --nodes=1  # should be equal to ntasks
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4gb  
#SBATCH --time=9:00:00
#SBATCH --output=output/Treiber.out
#SBATCH --error=output/Treiber.err
#SBATCH --job-name=Treiberskript
#module purge
#module load license_intel intel/18.0.3  #whatever version you need
#module load hdf/4.2.14    #and any other modules needed
./process_tape5_files

