#==============================================================================
#
# Makefile for LBLRTM_to_netCDF program
#
#==============================================================================

# Define macros
include $(CRTM_SOURCE_ROOT)/make.macros

# This makefile
MAKE_FILE = Makefile

# Executable file
EXE_FILE = LBLRTM_to_netCDF

# Source files to link
SRC_FILES = Type_Kinds.f90 \
            File_Utility.f90 \
            Message_Handler.f90 \
            Compare_Float_Numbers.f90 \
            netCDF_Utility.f90 \
            netCDF_Dimension_Utility.f90 \
            netCDF_Attribute_Utility.f90 \
            netCDF_Variable_Utility.f90 \
            Tau_Production_Parameters.f90 \
            Tau_Production_Utility.f90 \
            LBLRTM_Parameters.f90 \
            LBLRTM_Utility.f90 \
            LBLRTM_Fhdr_IO.f90 \
            LBLRTM_Phdr_IO.f90 \
            LBLRTM_Panel_IO.f90 \
            LBLRTM_Layer_IO.f90 \
            LBLRTM_netCDF_IO.f90

# Obj files used in link phase
OBJ_FILES = ${SRC_FILES:.f90=.o} \
            $(EXE_FILE).o

# Include and library definitions
NC4_DIR=/opt/netcdf4/4.3.3-intel-15.0-2
HDF_DIR=/opt/hdf5/1.8.14-intel-15.0-2
HDF4_DIR=/opt/hdf4/4.2.9-intel-15.0-2

INCLUDES = -I$(NC4_DIR)/include
LIBRARIES = -L$(NC4_DIR)/lib -lnetcdf

# Define common make targets (all, build, clean, install)
include $(CRTM_SOURCE_ROOT)/make.common_targets

# Source link creation and removal
#create_links:
#	@linkfiles $(CRTM_SOURCE_ROOT) $(SRC_FILES)

#remove_links:
#	@unlinkfiles $(SRC_FILES)

# Squeaky clean target
#realclean: clean remove_links

# Source dependency lists
include make.dependencies

# Define default rules
include $(CRTM_SOURCE_ROOT)/make.rules
